version: "3"

networks:
  mynetwork:

services:
  loldle-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/loldle-frontend
    container_name: loldle-frontend
    depends_on:
      - loldle-api
    ports:
      - 80:80
      - 443:443
      - 8241:8241
    restart: unless-stopped
    volumes:
      - /root/infiniteloldle/frontend/infiniteloldle.com.pem:/root/infiniteloldle/frontend/infiniteloldle.com.pem
      - /root/infiniteloldle/frontend/infiniteloldle.com.key:/root/infiniteloldle/frontend/infiniteloldle.com.key
    networks:
      - mynetwork
    healthcheck:
      test: nc -z -v localhost 80
      interval: 15s
      timeout: 5s
      retries: 10

  loldle-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/loldle-api
    container_name: loldle-api
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    environment:
      - DOCKER_APP_PORT=8080
    networks:
      - mynetwork
    healthcheck:
      test: 'wget --header="User-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.11 Infiniteloldle.com Health-Check" -nv -t1 --spider http://localhost:8080'
      interval: 15s
      timeout: 5s
      retries: 1